apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: renren-fast
  name: renren-fast
spec:
  ports:
  - name: "8280"
    port: 8280
    targetPort: 8080
  selector:
    io.kompose.service: renren-fast
status:
  loadBalancer: {}
