apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: renren-fast
  name: renren-fast
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: renren-fast
    spec:
      containers:
      - env:
        - name: spring.profiles.active
          value: dev
          image: 10.234.138.130:5000/renren/fast
        name: renren-fast
        ports:
        - containerPort: 8280
        resources: {}
      restartPolicy: Always
status: {}
